apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: logstash
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
    - name: beats
      port: {{ .Values.service.beatsPort }}
      targetPort: 5044
      protocol: TCP
  selector:
    app: logstash
    release: {{ .Release.Name }}