apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: storage
              mountPath: /var/lib/grafana
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-grafana-config
        - name: datasources
          configMap:
            name: {{ .Chart.Name }}-grafana-datasources
        - name: dashboard-provider
          configMap:
            name: {{ .Chart.Name }}-grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: {{ .Chart.Name }}-grafana-dashboards
        - name: storage
          emptyDir: {}