apiVersion: v1
kind: ConfigMap
metadata:
  name: front-ui-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "{{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "{{ .Values.env.SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT }}"
  ACCOUNTS_SERVICE_URL: "{{ .Values.env.ACCOUNTS_SERVICE_URL }}"
  EXCHANGE_SERVICE_URL: "{{ .Values.env.EXCHANGE_SERVICE_URL }}"
  CASH_SERVICE_URL: "{{ .Values.env.CASH_SERVICE_URL }}"
  TRANSFERS_SERVICE_URL: "{{ .Values.env.TRANSFERS_SERVICE_URL }}"
