apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-prometheus-pvc
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.prometheus.storage.storageClassName }}
  storageClassName: {{ .Values.prometheus.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}