# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources:
      - ingresses
    verbs: [ "get", "list", "watch" ]

  - nonResourceURLs:
      - /metrics
    verbs: ["get"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}
    namespace: {{ .Release.Namespace }}