apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
      protocol: TCP
  selector:
    app: prometheus
    release: {{ .Release.Name }}