server.port=8087
spring.application.name=exchange-service

#Keycloak (OAuth2)
spring.security.oauth2.client.provider.keycloak.issuer-uri=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER:http://localhost:8080/realms/bank-app}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT:http://localhost:8080/realms/bank-app/protocol/openid-connect/certs}

#Kafka-Consumer
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=exchange-rates
spring.kafka.consumer.properties.spring.json.trusted.packages="*"
spring.kafka.topic.exchange=actual-rates

#Actuator & Metrics
management.endpoints.web.exposure.include=health,info,loggers,refresh,metrics,prometheus,traces
management.endpoint.health.show-details=always

management.tracing.enabled=true
management.tracing.sampling.probability=${TRACING_SAMPLE_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans

#Logs
logging.pattern.console=%d{yyyy-MM-dd - HH:mm:ss.SSS (XXX)} %highlight(%5p) %clr(${PID}){magenta} ---> [%X{traceId:-}/%X{spanId:-}] [%clr(%t){green}] %clr(%c{36}){cyan} : %m%n
spring.output.ansi.enabled=always
logging.level.com.bank=INFO
logging.level.web=INFO
logging.level.org.springframework.web.reactive=INFO
logging.level.kafka=INFO
logging.level.root=INFO
