apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bestbank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
      - host: bank.local
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: front-ui
                  port:
                    number: 8085
      - host: keycloak.local
        http:
          paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: keycloak
                    port:
                      number: 8080