replicaCount: 1

image:
  repository: front-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8085
  type: ClusterIP
  targetPort: 8085

env:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_SECRET: "TJ6sMrcWSAEqp54QEamryjy1hYB7dwVg"
  ACCOUNTS_SERVICE_URL: "http://accounts-service:8081"
  EXCHANGE_SERVICE_URL: "http://exchange-service:8087"
  CASH_SERVICE_URL: "http://cash-service:8083"
  TRANSFERS_SERVICE_URL: "http://transfers-service:8082"