replicaCount: 1

image:
  repository: accounts-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8081
  type: ClusterIP
  targetPort: 8081

env:
  DB_HOST: "database-postgresql"
  DB_NAME: "AccountsDB"
  DB_PORT: "5432"
  SPRING_DATASOURCE_USER: "postgres"
  SPRING_DATASOURCE_PASSWORD: "Nikita1995"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_SECRET: "q3rpxNJ0K4zIKEOM0AaTTwQIDB2bLLkD"