apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-elasticsearch-pvc
  labels:
    app: elasticsearch
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}