server.port=8086
spring.application.name=blocker-service

#Keycloak (OAuth2)
spring.security.oauth2.client.provider.keycloak.issuer-uri=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER:http://localhost:8080/realms/bank-app}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT:http://localhost:8080/realms/bank-app/protocol/openid-connect/certs}

#Actuator & Metrics
management.endpoints.web.exposure.include=health,info,loggers,metrics,prometheus,traces
management.endpoint.health.show-details=always

management.tracing.enabled=true
management.tracing.sampling.probability=${TRACING_SAMPLE_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
management.tracing.propagation.type=b3

#Prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.server.errors=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.service=blocker-service

#Logs
logging.pattern.console=%d{yyyy-MM-dd - HH:mm:ss.SSS (XXX)} %highlight(%5p) %clr(${PID}){magenta} ---> [%X{traceId:-}/%X{spanId:-}] [%clr(%t){green}] %clr(%c{36}){cyan} : %m%n
spring.output.ansi.enabled=always
logging.level.com.bank=INFO
logging.level.web=INFO
logging.level.org.springframework.web.reactive=INFO
logging.level.kafka=INFO
logging.level.root=INFO