apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-service-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "{{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "{{ .Values.env.SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT }}"
  ACCOUNTS_SERVICE_URL: "{{ .Values.env.ACCOUNTS_SERVICE_URL }}"
  BLOCKER_SERVICE_URL: "{{ .Values.env.BLOCKER_SERVICE_URL }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"