apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-service-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "{{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "{{ .Values.env.SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
  TRACING_SAMPLE_PROBABILITY: "{{ .Values.env.TRACING_SAMPLE_PROBABILITY }}"
  ZIPKIN_BASE_URL: "{{ .Values.env.ZIPKIN_BASE_URL }}"
