apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-service-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "{{ .Values.env.SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "{{ .Values.env.SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT }}"
