prometheus:
  image:
    repository: prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090

  storage:
    enabled: true
    size: 5Gi
    storageClassName: "hostpath"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  retention: "15d"