{
 "title": "BestBank - Финансовые бизнес-метрики",
 "description": "Дэшборд бизнес-метрик приложения",
 "tags": [
  "bestbank",
  "business",
  "transactions"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Процентное соотношение успешности переводов",
   "type": "piechart",
   "description": "Процентное соотношение успешных и заблокированных переводов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bestbank_transfer_operation_allowed_total[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(bestbank_transfer_operation_blocked_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество переводов (rate) 5 min",
   "type": "timeseries",
   "description": "Вычисление количества переводов в течение 5 минут (успешных и неуспешных)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(bestbank_transfer_operation_allowed_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(bestbank_transfer_operation_failed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процентное соотношение успешности операций с наличными",
   "type": "piechart",
   "description": "Процентное соотношение успешных и заблокированных операций с наличными",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (bestbank_cash_operation_allowed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество операций с наличными (rate) 5 min",
   "type": "timeseries",
   "description": "Вычисление количества операций с наличными в течение 5 минут (успешных и неуспешных)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(bestbank_cash_operation_allowed_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(bestbank_cash_operation_blocked_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее число успешных переводов",
   "type": "stat",
   "description": "Общее количество успешных переводов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bestbank_transfer_operation_allowed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее число заблокированных переводов",
   "type": "stat",
   "description": "Общее количество заблокированных переводов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bestbank_transfer_operation_blocked_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее число успешных операций с наличными",
   "type": "stat",
   "description": "Общее количество успешных операций с наличными",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bestbank_cash_operation_allowed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее число заблокированных операций с наличными",
   "type": "stat",
   "description": "Общее количество заблокированных операций с наличными",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bestbank_cash_operation_blocked_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}