{
 "title": "BestBanlk - Метрики безопасности",
 "tags": [
  "bestbank",
  "security"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Процент успешных логинов",
   "type": "gauge",
   "description": "Процентное соотношение успешных логинов к общему количеству логинов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bestbank_login_success_total)\r\n/\r\n(\r\n  sum(bestbank_login_success_total)\r\n  +\r\n  sum(bestbank_login_failed_total)\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные логины за последние 5 min",
   "type": "timeseries",
   "description": "Показатель успешных входов в течение последних 5 минут",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bestbank_login_success_total{status=\"success\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Проверка обновления курсов валют (1 раз/мин)",
   "type": "stat",
   "description": "Проверка количества обновлений курсов валют в минуту",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(bestbank_rate_update_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Своевременность обновления курсов валют",
   "type": "gauge",
   "description": "Метрика актуальности курсов валют - вычисление времени последнего их обновления",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - timestamp(bestbank_rate_update_success_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные/неуспешные уведомления",
   "type": "timeseries",
   "description": "Метрика rate уведомлений (успешные/неуспешные) за 5 минут",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(bestbank_notification_success_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(bestbank_notification_failed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}