global:
  database:
    host: "database-postgresql"
    port: 5432
    user: "postgres"
    password: "Nikita1995"

# -----------------------------
# Accounts Service
# -----------------------------
accounts-service:
  replicaCount: 1
  image:
    repository: accounts-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8081
    type: ClusterIP
    targetPort: 8081

  env:
    DB_HOST: "database-postgresql"
    DB_NAME: "AccountsDB"
    DB_PORT: "5432"
    SPRING_DATASOURCE_USER: "postgres"
    SPRING_DATASOURCE_PASSWORD: "Nikita1995"
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "q3rpxNJ0K4zIKEOM0AaTTwQIDB2bLLkD"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Blocker Service
# -----------------------------
blocker-service:
  replicaCount: 1
  image:
    repository: blocker-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8086
    type: ClusterIP
    targetPort: 8086

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "NA1YP4xVAOQwqoVwc2x3Uj14qGxUNlvL"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Cash Service
# -----------------------------
cash-service:
  replicaCount: 1
  image:
    repository: cash-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8083
    type: ClusterIP
    targetPort: 8083

  env:
    DB_HOST: "database-postgresql"
    DB_NAME: "CashDB"
    DB_PORT: "5432"
    SPRING_DATASOURCE_USER: "postgres"
    SPRING_DATASOURCE_PASSWORD: "Nikita1995"
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "TcGDpj5RCoNZSwPEzbHIA4KlshZXzxyM"
    ACCOUNTS_SERVICE_URL: "http://accounts-service:8081"
    BLOCKER_SERVICE_URL: "http://blocker-service:8086"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Database (PostgreSQL)
# -----------------------------
database:
  image:
    repository: postgres
    tag: "13.21-alpine3.22"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

  env:
    POSTGRES_DB: database
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: Nikita1995

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "hostpath"

# -----------------------------
# Exchange Service
# -----------------------------
exchange-service:
  replicaCount: 1
  image:
    repository: exchange-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8087
    type: ClusterIP
    targetPort: 8087

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "m2ushCEPNLlF3e3Doeu1UHvxR5L4y97t"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Exchange Generator Service
# -----------------------------
exchange-generator:
  replicaCount: 1
  image:
    repository: exchange-generator
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8088
    type: ClusterIP
    targetPort: 8088

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "ls7aUcNo4FTeGuEGl5IQauxzpPMScgYc"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Front UI
# -----------------------------
front-ui:
  replicaCount: 1
  image:
    repository: front-ui
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8085
    type: ClusterIP
    targetPort: 8085

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "TJ6sMrcWSAEqp54QEamryjy1hYB7dwVg"
    ACCOUNTS_SERVICE_URL: "http://accounts-service:8081"
    EXCHANGE_SERVICE_URL: "http://exchange-service:8087"
    CASH_SERVICE_URL: "http://cash-service:8083"
    TRANSFERS_SERVICE_URL: "http://transfers-service:8082"

# -----------------------------
# Keycloak
# -----------------------------
keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.1.3"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  env:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin

  command:
    - start-dev
    - --import-realm
    - -Dkeycloak.import.strategy=OVERWRITE_EXISTING

# -----------------------------
# Notifications Service
# -----------------------------
notification-service:
  replicaCount: 1
  image:
    repository: notification-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8084
    type: ClusterIP
    targetPort: 8084

  env:
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "hAXOLsHew6GeFkliWveGjICtfYO29ZDK"
    SPRING_MAIL_USERNAME: "bestbank2025@yandex.ru"
    SPRING_MAIL_PASSWORD: "yczxsbvwwsyrfvlf"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Transfers Service
# -----------------------------
transfers-service:
  replicaCount: 1
  image:
    repository: transfers-service
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8082
    type: ClusterIP
    targetPort: 8082

  env:
    DB_HOST: "database-postgresql"
    DB_NAME: "TransfersDB"
    DB_PORT: "5432"
    SPRING_DATASOURCE_USER: "postgres"
    SPRING_DATASOURCE_PASSWORD: "Nikita1995"
    SPRING_PROFILES_ACTIVE: "kubernetes"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER: "http://keycloak:8080/realms/bank-app"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT: "http://keycloak:8080/realms/bank-app/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_SECRET: "cK5F2xDqqrKzA8C4r3Exa9N8VTnO3dsP"
    ACCOUNTS_SERVICE_URL: "http://accounts-service:8081"
    EXCHANGE_SERVICE_URL: "http://exchange-service:8087"
    BLOCKER_SERVICE_URL: "http://blocker-service:8086"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    TRACING_SAMPLE_PROBABILITY: "1.0"
    ZIPKIN_BASE_URL: "http://zipkin:9411"

# -----------------------------
# Kafka
# -----------------------------
kafka:
  enabled: true

  kafka:
    replicaCount: 1

    persistence:
      enabled: true
      size: 1Gi

    kraft:
      clusterId: "hPdNttqdQHCc6FTHW1NV_Q"
      nodeId: 1
      processRoles: "broker,controller"

    config:
      numPartitions: 3
      defaultReplicationFactor: 1
      minInsyncReplicas: 1
      logRetentionHours: 72

  kafkaUi:
    enabled: true

# -----------------------------
# Zipkin
# -----------------------------
zipkin:
  image:
    repository: openzipkin/zipkin
    tag: "3.5.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9411
    targetPort: 9411

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  replicaCount: 1

  storage:
    type: mem

# -----------------------------
# Prometheus
# -----------------------------
prometheus:
  image:
    repository: prom/prometheus
    tag: "3.9.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090

  storage:
    enabled: true
    size: 5Gi
    storageClassName: "hostpath"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  retention: "15d"

# -----------------------------
# Grafana
# -----------------------------
grafana:
  image:
    repository: grafana/grafana
    tag: "12.3.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

  adminUser: admin
  adminPassword: admin

  datasources:
    prometheus:
      name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# -----------------------------
# Elasticsearch
# -----------------------------
elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "9.2.4"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 9200
    transportPort: 9300

  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m

  persistence:
    size: 5Gi
    storageClassName: "hostpath"

  elasticsearch:
    javaOpts: "-Xms512m -Xmx512m"
    security:
      enabled: false
      enrollment: false

# -----------------------------
# Logstash
# -----------------------------
logstash:
  image:
    repository: docker.elastic.co/logstash/logstash
    tag: "9.2.4"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000
    beatsPort: 5044

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

  logstash:
    javaOpts: "-Xmx512m -Xms512m"

  kafka:
    bootstrapServers: "kafka:9092"

  elasticsearch:
    host: "elasticsearch"
    port: 9200

# -----------------------------
# Kibana
# -----------------------------
kibana:
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: "9.2.4"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5601

  replicaCount: 1

  elasticsearch:
    host: "elasticsearch"
    port: 9200

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

  kibana:
    server:
      name: "kibana"
      host: "0.0.0.0"
    elasticsearch:
      host: "http://elasticsearch:9200"
    security:
      enabled: false
      encryption:
        key:
          value: "min-32-byte-long-strong-encryption-key-value"