apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-service-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "{{ .Values.keycloak.issuerUri }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_SET_URI: "{{ .Values.keycloak.jwkSetUri }}"
