apiVersion: v1
kind: Secret
metadata:
  name: accounts-service-secret
type: Opaque
stringData:
  db-username: "{{ .Values.database.username }}"
  db-password: "{{ .Values.database.password }}"
  oauth-client-secret: "{{ .Values.oauth.frontui.clientSecret }}"